Repository Subham-Maity/StockOfSentence, pull requests merged in 2022-10, with the labels that each got.

#22 play button enhanced
  index.html
  script.js
  style.css
Labels: hacktoberfest2022, hacktoberfest

#93 Added Popup to inform guests of audio-spacebar functionality
  index.html
  script.js
  style.css
Labels: enhancement

#94 Text Show and Disappear Features
  audioplay.js
  index.html
  script.js
  style.css
Labels: bug, enhancement

#98 Added 12 movie quotes in dataset.js
  dataset.js
Labels: good first issue, hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#97 added new quotes in dataset.js
  dataset.js
Labels: enhancement, recheck

#99 Added New Quotes in dataset.js
  dataset.js
Labels: enhancement, recheck

#109 Movies quotes and inspiring character from all time best
  dataset.js
Labels: recheck

#107 inspirational added again
  dataset.js
Labels: recheck

#112 Add Les Misérables and 8 ½ quotes
  dataset.js
Labels: recheck

#117 Added more dialogues to the dataset
  dataset.js
Labels: enhancement, good first issue, hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#118 Added movie dialogues
  dataset.js
Labels: conflict solved

#120 Added random dialogues
  dataset.js
Labels: good first issue, hacktoberfest2022, hacktoberfest, hacktoberfest-accepted, zero conflict

#122 Added ten movie quotes
  dataset.js
Labels: conflict

#123 Added 10 dialogues of hollywood movies
  dataset.js
Labels: zero conflict, dev-check

#125 Docs: added 10 new quotes
  dataset.js
Labels: enhancement, hacktoberfest2022, hacktoberfest, hacktoberfest-accepted, contribute, conflict solved

#132 Contributing
  CONTRIBUTING.md
  dataset.js
Labels: enhancement, hacktoberfest2022, hacktoberfest, hacktoberfest-accepted, zero conflict, dev-check

#130 Additional quotes added to data set
  dataset.js
Labels: recheck, zero conflict, dev-check, need some change

#129 Update dataset.js
  dataset.js
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted, conflict solved, zero conflict

#135 Adding new dialouges
  dataset.js
Labels: recheck, new contributor, zero conflict, need some change
